# Generated by Django 5.0.6 on 2026-06-25 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductServices', '0005_alter_categories_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('INACTIVE', 'INACTIVE')], default='ACTIVE', max_length=255),
        ),
    ]
