# Generated by Django 5.0.6 on 2026-06-25 11:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductServices', '0006_categories_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='barcode',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='stock_alert_quantity',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='products',
            name='supplier_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supplier_id_products', to=settings.AUTH_USER_MODEL),
        ),
    ]
