# Generated by Django 5.0.6 on 2026-06-24 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserServices', '0007_rename_is_add_userpermissions_is_permission_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='profile_pic',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
